Add job that tags when there is a commit to main
instana/instana-agent-operator pull request #129
Opened 2024-01-25 10:25 UTC by Milica-Cvrkota-IBM

2024-01-25 12:40 UTC, konrad-ohms requested changes

2024-01-25 12:40 UTC, konrad-ohms commented on ci/pipeline.yaml
> +              git pull
I don't think you'll have git by default in the ubi8 minimal image:
```
$ docker run --rm -it registry.access.redhat.com/ubi8/ubi-minimal
[root@dbd98512b1e9 /]# git
bash: git: command not found
[root@dbd98512b1e9 /]# 
```

2024-01-31 11:00 UTC, FelixMarxIBM approved these changes

2024-01-31 13:25 UTC, FelixMarxIBM approved these changes

2024-01-31 13:40 UTC, FelixMarxIBM approved these changes

2024-01-31 13:41 UTC, merged