ci: Refactor creation of the public PRs
instana/instana-agent-operator pull request #166
Opened 2024-06-05 13:54 UTC by Milica-Cvrkota-IBM

Changes:
* extract common scripts
* if ANY instana-operator PR is open, don't create a new one
* make sure to rebase off of upstream before commiting changes

2024-06-06 09:07 UTC, konrad-ohms requested changes
Thanks, looks good in general.
I have a few remarks, especially using feature branches instead of main might be useful

2024-06-06 09:07 UTC, konrad-ohms commented on ci/scripts/commit-changes-to-public-repo.sh
> +git commit -s -m "$COMMIT_MESSAGE" --allow-empty
```suggestion
git commit -s -m "$COMMIT_MESSAGE"
# use force to ensure updated branches
# potential optimization -> check if changes on the remote and local branch are equal on a file level to not push a new commit if not necessary (might trigger a new pipeline run)
# we could do that by trying to fetch the remote branch and apply the changes, if not files changed, do not push it
git push origin "$PR_BRANCH_NAME" --force
```

2024-06-06 09:07 UTC, konrad-ohms commented on ci/scripts/create-pr.sh
> +-d "{\"title\":\"$COMMIT_MESSAGE\",\"head\":\"instana:main\",\"base\":\"main\"}"
Just a matter of styling, I prefer to intend the command flags if they are split into multiple lines, but no hard requirement.
But if we decide to use a feature branch, we need to adjust the PR creation accordingly.
```suggestion
curl \
  -fX POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer $GH_API_TOKEN" \
  https://api.github.com/repos/$OWNER/$REPO/pulls \
  -d "{\"title\":\"$COMMIT_MESSAGE\",\"head\":\"instana:$PR_BRANCH_NAME\",\"base\":\"main\"}"
```

2024-07-01 10:12 UTC, Milica-Cvrkota-IBM commented on ci/scripts/commit-changes-to-public-repo.sh
> +    EXISTING_PR_INFO_JSON=$(echo "$PR_LIST_JSON" | jq ".[] | select(.title | contains(\"$OPERATOR_PUBLIC_PR_NAME\"))")
Hmm good question. In the past we had to manually create the PRs sometimes that were real PRs that should be considered for a release promotion. If we agree that we can't do this going forward, we can add the user ID to the check

2024-07-01 14:04 UTC, Milica-Cvrkota-IBM commented on ci/scripts/commit-changes-to-public-repo.sh
> +    fi
I'm not sure that the changes would change in the second iteration once the PR is already created with the new changes

2024-07-01 14:05 UTC, Milica-Cvrkota-IBM commented on ci/scripts/commit-changes-to-public-repo.sh
> +git push --force
We have a `git checkout` now

2024-07-02 09:13 UTC, konrad-ohms approved these changes
Looks good, thanks :slightly_smiling_face: 
I am wondering if we should add some body to the PRs the automation create, but it looks like it is not required by Red Hat, so just personal preference and we could not add much info anyways I think

2024-07-02 10:00 UTC, merged